

---
    ansible_user: administrateur
    ansible_password: Comete@44

    # psrp
    ansible_connection: psrp
    ansible_psrp_auth: credssp

    # winrm
    ansible_connection: winrm
    ansible_winrm_transport: credssp
  - name: Windows Update
    hosts: windows
    tasks:
      - name: Install all update
        ansible.windows.win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - Update Rollups
            - Updates
            - Application
            - Definition Updates
          log_path: C:\ansible_wu.txt


