

---
  - name: Windows Update
    hosts: windows
    tasks:
      - name: Install all update
        ansible.windows.win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - Update Rollups
            - Updates
            - Application
            - Definition Updates
        vars:
           ansible_become_user: "{{ administrateur }}"
           ansible_become_password: "{{ Comete@44 }}"
           log_path: C:\ansible_wu.txt


